### ISSUE TITLE
New files are being erased

### ISSUE THREAD

**Issue by MSny** [tibor-kocsis/octobercms-heroku#1]
Loved your quick guide on setting up on heroku. I followed the steps and was able to quickly setup, but I noticed that all the files I created in the demo file through the backend CMS were erased after a short time. 

I've used Incognito to check that I was able to navigate to a newly created page, but after a very short while, it would all be erased and I could no longer hit that page, only the content I originally pushed up remaining. Do you how I can stop heroku/october from deleting the new files I make?

**Comment by tibor-kocsis** [comment]
It is because of the heroku's filesystem.

https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem

So you should not edit any of the template files in browser, all the changes must be under version control, and pushed with git to heroku. The ephemeral filesystem is a problem with the user uploaded files too, and heroku suggest to use S3 to store these files. I will continue the guide with S3 soon, but i think there is no easy solution to keep the modifications made under backend/cms in a heroku deployment.
